name: Feature Testing

on:
    push:

permissions:
    id-token: write
    contents: read

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "Hello World!"