name: Feature Testing

on:
    push:

permissions:
    id-token: write
    contents: read

jobs:
    Build:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
              
            - name: Install Dependecies
              run: npm ci
            
            - name: Run Tests
              run: npm run test 